GET http://localhost:8080/platforms
Accept: application/json

###

GET http://localhost:8080/platforms/1
Accept: application/json

###

POST http://localhost:8080/platforms
Content-Type: application/json

{
  "name": "Xbox One"
}

###

DELETE http://localhost:8080/platforms/1
Accept: application/json